version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: clone submodules
          command: git submodule update --recursive --init
      - run:
          name: update node version
          command: |
            sudo apt-get purge node
            curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
            sudo apt-get install -y nodejs
            ln -s /usr/bin/nodejs /usr/bin/node
      - run:
          name: update python version
          command: |
            pyenv global 3.5.2
            python3 -m pip install --upgrade pip
      - run:
          name: npm install
          command: npm link . && npm install --unsafe-perm=true
      - run: nodejs -v
      - run: npm -v
      - run:
          name: run tests
          command: npm test
