version: 2

jobs:
  build:
    docker:
      - image: architectio/architect-cli-base:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: clone submodules
          command: git submodule update --recursive --init
      - run:
          name: npm install
          command: rm -rf node_modules && npm install --unsafe-perm=true && npm link . && npm install --unsafe-perm=true
      - run:
          name: test docker
          command: |
            mkdir -p /opt/protoc/addition_service
            docker run -v /root/project/test/calculator-example/addition-service:/defs -v /tmp:/opt/protoc --user $(id -u):$(id -g) architectio/protoc-all -f /opt/protoc/addition_service/service.proto -i /opt/protoc -l node -o architect_services
      - run:
          name: run tests
          command: npm test
