version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: clone submodules
          command: git submodule update --recursive --init
      - run: pyenv global 3.5.2
      - run: python3 --version
      - run: python3 -m pip --version
      - run:
          name: npm install
          command: rm -rf node_modules && npm install --unsafe-perm=true && npm link . && npm install --unsafe-perm=true
      - run: mkdir -p /opt/protoc/addition_service
      - run: ls -l /opt/protoc/addition_service
      - run:
          name: docker run protoc-all
          command: |
            docker run -v /root/project/test/calculator-example/addition-service:/defs -v /tmp:/opt/protoc --user $(id -u):$(id -g) architectio/protoc-all -f /opt/protoc/addition_service/service.proto -i /opt/protoc -l node -o architect_services
      - run:
          name: run tests
          command: npm test
