version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: clone submodules
          command: git submodule update --recursive --init
      - run:
          name: update docker
          command: curl -sSL https://get.docker.com/ | sh
      - run:
          name: update node version
          command: |
            curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            source ~/.profile
            nvm install 11
            nvm alias default 11
            nvm use default
            node -v
      - run:
          name: update python version
          command: |
            pyenv global 3.5.2
            python3 -m pip install --upgrade pip
      - run:
          name: npm install
          command: |
            npm link .
            npm install --unsafe-perm=true
      - run:
          name: python test
          command: |
            source ~/.profile
            python3 -m pip install Click grpcio
            python3 -m pip freeze
            ls -l /opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/
      - run:
          name: npm test
          command: |
            source ~/.profile
            npm rebuild
            npm test
