version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: clone submodules
          command: git submodule update --recursive --init
      - run: pyenv global 3.5.2
      - run: python3 -m pip install --upgrade pip
      - run:
          name: npm install
          command: npm link . && npm install --unsafe-perm=true
      - run:
          name: run tests
          command: npm test
