version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: clone submodules
          command: git submodule update --recursive --init
      - run:
          name: update node version
          command: |
            curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh -o install_nvm.sh | bash
            source ~/.profile
            nvm install 11
            nvm alias default 11
            nvm use default
      - run:
          name: update python version
          command: |
            pyenv global 3.5.2
            python3 -m pip install --upgrade pip
      - run:
          name: npm install
          command: npm link . && npm install --unsafe-perm=true
      - run: |
          nvm use default
          node -v
      - run: npm -v
      - run:
          name: run tests
          command: npm test
