module.exports = {
  publicRuntimeConfig: {
    NEXT_PUBLIC_OAUTH_AUTH_URL: process.env.NEXT_PUBLIC_OAUTH_AUTH_URL,
    NEXT_PUBLIC_OAUTH_TOKEN_URL: process.env.NEXT_PUBLIC_OAUTH_TOKEN_URL,
    NEXT_PUBLIC_OAUTH_LOGOUT_URL: process.env.NEXT_PUBLIC_OAUTH_LOGOUT_URL,
    NEXT_PUBLIC_OAUTH_CLIENT_ID: process.env.NEXT_PUBLIC_OAUTH_CLIENT_ID,
    NEXT_PUBLIC_OAUTH_SCOPES: process.env.NEXT_PUBLIC_OAUTH_SCOPES,
    NEXT_PUBLIC_SELF_URL: process.env.NEXT_PUBLIC_SELF_URL,
  },
};
